In [1]:
#How do you calculate percentiles with Python/ NumPy?
import numpy as np
a = np.array([1,2,3,4,5])
p = np.percentile(a, 50) #Returns 50th percentile, e.g. median
print(p)

3.0


In [6]:
a=[1,2,3,3,2]
b=[1,2,3,4,5]
a=np.array(a)
b=np.array(b)
a+b


array([2, 4, 6, 7, 7])

In [7]:
a>2

array([False, False,  True,  True, False])

In [8]:
a[a>2]

array([3, 3])

In [13]:
#create an array with 10 random integers
a=np.random.randint(1,100,10)
a

array([95, 80, 21, 85, 27, 61, 57, 32,  7, 62])

In [35]:
b=np.ones(6) * 11
b.reshape(2,3)

array([[11., 11., 11.],
       [11., 11., 11.]])

In [39]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [45]:
np.arange(0,20).reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [48]:
np.arange(0,8).reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [49]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
np.random.rand()

0.43788681537990026

In [51]:
np.random.rand(25)

array([0.82012219, 0.50751409, 0.62348579, 0.14598442, 0.64326786,
       0.50920842, 0.78338623, 0.05211857, 0.62548931, 0.24047298,
       0.14842014, 0.51285249, 0.48129726, 0.06054598, 0.22465674,
       0.44218263, 0.32857704, 0.5450638 , 0.33468087, 0.59028368,
       0.06479089, 0.07758415, 0.4521835 , 0.77932236, 0.86372532])

In [54]:
np.array(33)

array(33)

In [68]:
#20 numbers between the range 0,20 with equal space(*********imp)
np.linspace(0,40,20)

array([ 0.        ,  2.10526316,  4.21052632,  6.31578947,  8.42105263,
       10.52631579, 12.63157895, 14.73684211, 16.84210526, 18.94736842,
       21.05263158, 23.15789474, 25.26315789, 27.36842105, 29.47368421,
       31.57894737, 33.68421053, 35.78947368, 37.89473684, 40.        ])

In [70]:
m=np.arange(1,26).reshape(5,5)
m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [86]:
j=m[2:,1:]
j

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [73]:
m[3:4,4:]

array([[20]])

In [75]:
m[3,4]

20

In [83]:
n=m[1:4,1].reshape(3,1)
n

array([[ 7],
       [12],
       [17]])

In [91]:
j

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [92]:
j.sum()

222

In [93]:
j.sum(axis=0)

array([51, 54, 57, 60])

In [94]:
j.sum(axis=1)

array([54, 74, 94])